=== TomVanRoy/XML-Fundamentals/XML Fundamentals/XML Fundamentals Taken Materiaal/bioschoopfilm.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:vdab="http://www.vdab.be/reisbestemming"
        targetNamespace="http://www.vdab.be/reisbestemming"
        elementFormDefault="qualified">
  <complexType name="Akteurs">
    <sequence>
      <element name="akteur" maxOccurs="unbounded" />
    </sequence>
  </complexType>
  <complexType name="Genres">
    <sequence>
      <element name="genre" maxOccurs="unbounded" />
    </sequence>
  </complexType>
  <complexType name="Film">
    <sequence>
      <element name="titel" />
      <element name="genres" type="vdab:Genres" />
      <element name="duurtijd" type="positiveInteger" />
      <element name="regisseur" />
      <element name="akteurs" type="vdab:Akteurs" />
    </sequence>
  </complexType>
  <element name="film" type="vdab:Film" />
</schema>

=== TomVanRoy/XML-Fundamentals/XML Fundamentals/XML Fundamentals Taken Materiaal/Bioschoopfilm.xml
<?xml version="1.0" encoding="utf-8"?>
<film xmlns="http://www.vdab.be/bioschoopfilm"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.vdab.be/bioschoopfilm Bioschoopfilm.xsd">
  <titel>Miss Peregrine's Home for Peculiar Children</titel>
  <genres>
    <genre>Fantasy</genre>
    <genre>Avontuur</genre>
  </genres>
  <duurtijd>127</duurtijd>
  <regisseur>Tim Burton</regisseur>
  <akteurs>
    <akteur>Eva Green</akteur>
    <akteur>Judi Dench</akteur>
    <akteur>Samuel L. Jackson</akteur>
    <akteur>Asa Butterfield</akteur>
    <akteur>Ella Purnell</akteur>
    <akteur>Terence Stamp</akteur>
  </akteurs>
</film>
