=== TomVanRoy/XML-Fundamentals/XML Fundamentals/XML Fundamentals Taken Materiaal/muziekfestival.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:vdab="http://www.vdab.be/festival"
        targetNamespace="http://www.vdab.be/festival"
        elementFormDefault="qualified">
  <simpleType name="Begin">
    <restriction base="time">
      <minInclusive value="12:00:00"/>
    </restriction>
  </simpleType>
  <simpleType name="Datum">
    <restriction base="date">
      <minInclusive value="2016-07-08" />
      <maxInclusive value="2016-07-09" />
    </restriction>
  </simpleType>

  <complexType name="Optreden">
    <attribute name="begin" use="required" type="vdab:Begin" />
    <attribute name="einde" use="required" type="time" />
    <attribute name="artiest" use="required" />
  </complexType>
  <complexType name="Dag">
    <sequence>
      <element name="optreden" maxOccurs="unbounded" type="vdab:Optreden" />
    </sequence>
    <attribute name="datum" use="required" type="vdab:Datum" />
  </complexType>
  <complexType name="Festival">
    <sequence>
      <element name="dag" maxOccurs="unbounded" type="vdab:Dag"/>
    </sequence>
  </complexType>

  <element name="festival" type="vdab:Festival">
    <key name="dagKey">
      <selector xpath="vdab:dag" />
      <field xpath="@datum" />
    </key>
  </element>
</schema>

=== TomVanRoy/XML-Fundamentals/XML Fundamentals/XML Fundamentals Taken Materiaal/muziekfestival.xml
<?xml version="1.0" encoding="utf-8" ?>
<festival xmlns="http://www.vdab.be/festival"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.vdab.be/festival Muziekfestival.xsd">
  <dag datum="2016-07-08">
    <optreden begin="18:20:00" einde="19:30:00" artiest="Laura Mvala" />
    <optreden begin="20:00:00" einde="21:15:00" artiest="Charles Bradley" />
    <optreden begin="21:45:00" einde="23:00:00" artiest="Gregory Porter" />
    <optreden begin="23:30:00" einde="01:00:00" artiest="Damien Rice" />
  </dag>
  <dag datum="2016-07-09">
    <optreden begin="18:20:00" einde="19:30:00" artiest="Kurt Vile" />
    <optreden begin="20:00:00" einde="21:10:00" artiest="SX" />
    <optreden begin="21:45:00" einde="23:00:00" artiest="Cinematic Orchestra" />
    <optreden begin="23:40:00" einde="01:00:00" artiest="Air" />
  </dag>
</festival>
