=== TomVanRoy/XML-Fundamentals/XML Fundamentals/XML Fundamentals Taken Materiaal/Reisbestemming.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:vdab="http://www.vdab.be/reisbestemming"
        targetNamespace="http://www.vdab.be/reisbestemming"
        elementFormDefault="qualified">
  <complexType name="Hotel">
    <attribute name="naam" use="required" />
    <attribute name="prijs" use="required" type="nonNegativeInteger" />
  </complexType>
  <complexType name="Excursie">
    <attribute name="naam" use="required" />
    <attribute name="prijs" use="required" type="nonNegativeInteger" />
    <attribute name="aantaldagen" use="required" type="nonNegativeInteger" />
  </complexType>
  <complexType name="Hotels">
    <sequence>
      <element name="hotel" maxOccurs="unbounded" type="vdab:Hotel" />
    </sequence>
  </complexType>
  <complexType name="Excursies">
    <sequence>
      <element name="excursie" minOccurs="0" maxOccurs="unbounded" type="vdab:Excursie" />
    </sequence>
  </complexType>
  <complexType name="Reisbestemming">
    <sequence>
      <element name="naam" />
      <element name="hotels" type="vdab:Hotels" />
      <element name="excursies" type="vdab:Excursies" />
    </sequence>
  </complexType>
  <element name="reisbestemming" type="vdab:Reisbestemming" />
</schema>

=== TomVanRoy/XML-Fundamentals/XML Fundamentals/XML Fundamentals Taken Materiaal/Reisbestemming.xml
<?xml version="1.0" encoding="utf-8"?>
<reisbestemming xmlns="http://www.vdab.be/reisbestemming"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.vdab.be/reisbestemming Reisbestemming.xsd">
  <naam>Kreta</naam>
  <hotels>
    <hotel naam="Time to smile Sundance" prijs="510"/>
    <hotel naam="Suneo club Chrissi" prijs="610"/>
    <hotel naam="Suneo club Althea Village" prijs="801"/>
    <hotel naam="Aquila Porto Rethymnon" prijs="544"/>
  </hotels>
  <excursies>
    <excursie naam="Spinalonga" prijs="54" aantaldagen="1"/>
    <excursie naam="Jeep safari" prijs="78" aantaldagen="2"/>
    <excursie naam="Knossos en Heraklion" prijs="55" aantaldagen="1"/>
  </excursies>
</reisbestemming>
